### ISSUE TITLE
No subdirectory filter

### ISSUE THREAD

**Issue by JukeboxBill** [mrdokenny/History-AutoDelete#20]
It's a very useful add-on, but it is not possible to filter specific subdirectories in a website. For instance, I manage a photoalbum website on my brothers domain witch is http://www.name.nl/~fotoalbum.
 It generates a lot of history-entries which I would like to filter, but not the full website of my brother.
 When I add the full domainpath to the list of URL's it adds name.nl but leaves /~fotoalbum out of it.

**Comment by mrdokenny** [comment]
Something like this as well as #16 would require a restructure of how I store my whitelist, so it may or may not happen. 

But thank you for using it.

**Comment by mrdokenny** [comment]
This was added in 2.0.0
