### ISSUE TITLE
Problem with History AutoDelete 2.0.0

### ISSUE THREAD

**Issue by sleek22** [mrdokenny/History-AutoDelete#23]
I have history set to 90 days. My history shows items from mid-May to mid-August, i.e., 90 days.

Right after updating, my history now shows items from mid-June to mid-August, i.e., 60 days.

This despite not changing any settings and History AutoDelete still showing 90 days as a setting. It appears to have erased one month exactly, i.e., it thinks 90 days is 60 days.

I reinstalled a backup of Firefox, installed the new version again and the same thing happened in exactly the same way, i.e., lost one month of history.

**Comment by mrdokenny** [comment]
Hmm sorry about that. I tested the migration code numerous times, so I'm not entirely sure what might be the problem. Does your domain list import?

**Comment by mrdokenny** [comment]
2.0.0 was auto approved by a bot. Unfortunately, 2.0.1 has to go through review now.

I think that if you are trying to update, the workaround is to disable the Keep History for... setting, update, then enable the keep history setting.

**Comment by sleek22** [comment]
Thank you for the quick response. I'm back on the older version which is working just fine and will wait for the new version.

Thank you so much for taking the time to make this excellent add-on.

**Comment by mrdokenny** [comment]
@sleek22 If you like, you can try the workaround (Unchecking the Keep History for... setting will disable the automatic history cleanup). 

Another option to avoid the migration process is go into your `profile\browser-extension-data\{7e79d10d-9667-4d38-838d-471281c568c3}` and delete the storage.js (this is where WebExtensions keep their data now). 

This will start the extension in a clean slate but you will have to redo your settings (which shouldn't be too bad in 2.0.0+ since you can use wildcards in the domain now 😄 )

**Comment by sleek22** [comment]
New problem...

I tried the first method you suggested by unchecking "Keep History for" and installed the latest version. However, I was unable to re-enable it after the installation. I click in the checkbox and nothing happens, nor on the box below which I had checked and it doesn't respond either. (the days counter will respond however when I click on up or down).

All the checkboxes however, are unresponsive. Restarting Firefox had no effect.

**Comment by mrdokenny** [comment]
>I tried the first method you suggested by unchecking "Keep History for" and installed the latest version. However, I was unable to re-enable it after the installation. I click in the checkbox and nothing happens, nor on the box below which I had checked and it doesn't respond either. (the days counter will respond however when I click on up or down).

I removed the Save/Cancel buttons cause it's not needed anymore, since the UI basically reflects the true state of that setting automatically (this is what I like about React/Redux). So if it's checked, then it's `true` for that setting. 

Does it still check/uncheck though?

You can test if a setting is working by Enable/Disable `Show Number of Visits In Browser Icon` and refreshing a page to see if that shows a number in the icon.

>Old version: pointer symbol on white space and over checkboxes, text selection tool when over text.
New version: pointer symbol on white space, hand symbol on checkboxes and when over text.

That's expected since it makes sense to click on the text to active the respective checkbox (makes it easier for mobile as well).

**Comment by mrdokenny** [comment]
Edit: Now I see the problem, apparently the checkboxes activate, but only in Nightly 57+ and Chrome for some odd reason? I'll have to do more testing. Looks like I'll update the compatibility to Nightly for now. 

Also you can switch between 1.X.X and 2.X.X since the old settings haven't been deleted.

**Comment by mrdokenny** [comment]
Hey @sleek22 , do you mind testing the version I posted in the beta versions and see if the checkboxes work? The first migration code I forgot to add an id which caused the settings page checkboxes to be confused which settings to be updated.

In this one, I added a settings validator, which will detect if there's anything wrong with the settings object and attempts to fix it (in this case by adding an id).

So I take back what I said about it only working in Nightly 57+ and Chrome as they already have an id.

Thanks for testing!

https://addons.mozilla.org/en-US/firefox/addon/history-autodelete/versions/beta

**Comment by sleek22** [comment]
No problem, my pleasure.

I just installed beta version 2.0.2b1, it did not delete the month of entries like before and the checkboxes are now working. The List of Expressions has also carried over. 

The Welcome page shows that it has deleted 1 entry and I expect that number to grow as the day goes on. For now, I assume it's working. I'll report back if I see any problems.

**Comment by sleek22** [comment]
New problem...

Because it stays on reporting only 1 history entry in total, I changed the number of days from 90 to 80 and nothing happened. I even restarted Firefox and it still shows 1 history entry in total, i.e., no deleted history for this session.

I went back to my old Firefox version with the old History AutoDelete which is the one I was using just before trying out the beta version and History AutoDelete immediately removed 43 entries.

Checking it again just now shows it has just moved to 44 entries.

It may be that the new version is not actually deleting entries.

**Comment by mrdokenny** [comment]
>Because it stays on reporting only 1 history entry in total, I changed the number of days from 90 to 80 and nothing happened. I even restarted Firefox and it still shows 1 history entry in total, i.e., no deleted history for this session.

Oh yeah, I think I removed it counting the history deleted from the "Keep History for.. setting", as it only counts the ones that are auto deleted via an visiting a url. <--If you still think it's a good idea, I can reintroduce it.

History is still auto deleted though via the "Keep History for.." setting

Also got rid of the session delete counter.

>As I wrote this, history deleted this session has moved to 45 entries. So I think that there is something wrong in the beta version as it showed no changes while I was testing.

The migration doesn't import your counter, so it'll start at 0.

Side note: The `places.sqlite` contains your history I believe, so you wouldn't have to restore your old profile everytime.

**Comment by sleek22** [comment]
>>Also got rid of the session delete counter.<<

I like the old version better. It was simple to understand. And because it was more verbose, you could see that it was doing its job.

>>The places.sqlite contains your history I believe, so you wouldn't have to restore your old profile everytime.<<

Yes, you are right. I thought about that after writing my comment. But that is still a problem because over time, I make changes to bookmarks, adding, deleting, and sorting bookmarks. Those are also part of places.sqlite. Also, I lose "visited links" which is how I know how far to go down in forums that constantly update.

The reason that I restore the whole profile is that sometimes new add-ons can make changes in other parts of Firefox including clashing with other add-ons. (I have about a hundred add-ons installed so the extra insurance is worth it).

**Comment by mrdokenny** [comment]
>Also got rid of the session delete counter.<<
I like the old version better. It was simple to understand.

Since it was a pretty good redesign of the code (I'd say about 75%-85%), it was one of the things that I didn't reimplement. Though there's nothing stopping me from adding it again if there's enough demand.

**Comment by ke-d** [comment]
Since I think all the main blockers that prevents the usage of the extension have been fixed, I'm going to ahead and push 2.0.2 out since 2.X.X hasn't been "manually" reviewed yet, and I want that to be reviewed asap so that future versions of 2.X.X won't take as long.
