### ISSUE TITLE
Mostly fine but...

### ISSUE THREAD

**Issue by SteveP-UK** [mrdokenny/History-AutoDelete#47]
I'm using the latest version of Firefox and I'm not seeing a menu option anywhere for...
- Import and Export your list of domains
- Keep history for X days (auto delete older history)
- Counts the total number history deleted
- Icon shows you how many times that domain's entries show up in your history

Can you advise where these options are located?

Thanks for developing this extension! :)

Steve

**Comment by SteveP-UK** [comment]
> 
> 
> I'm using the latest version of Firefox and I'm not seeing a menu option anywhere for...
> 
>     * Import and Export your list of domains
> 
>     * Keep history for X days (auto delete older history)
> 
>     * Counts the total number history deleted
> 
>     * Icon shows you how many times that domain's entries show up in your history
> 
> 
> Can you advise where these options are located?
> 
> Thanks for developing this extension! :)
> 
> Steve

Ignore my question - I found the options! :)

**Comment by grahamperrin** [comment]
@SteveP-UK you can close your own issue. Thanks.

**Comment by SteveP-UK** [comment]
Must get to SpecSavers!
